variables: 
 GIT_STRATEGY: fetch
 GIT_SUBMODULE_STRATEGY: recursive
 
stages: 
 - prep
 - build
 - package

apply_patches: 
 stage: prep 
 script: 
 - cd ./opcua-plugin/lwm2m-server 
 - git apply wakaama.patch 
 - cd ../../
 allow_failure: true
 
check_dependencies: 
 stage: prep
 script: 
 - cd ~/opcua-dev-workspace/opcua_project/opcua-plugin
 - ./.check-dependencies

build_x86_server_release: 
 stage: build
 script: 
  - ./opcua-build-x86-amd64-release.sh

build_x86_server_debug: 
 stage: build
 script: 
  - ./opcua-build-x86-amd64-debug.sh 

build_arm_server_release: 
 stage: build
 script: 
  - ./opcua-build-arm-release.sh

build_arm_server_debug:
 stage: build
 script: 
  - ./opcua-build-arm-debug.sh
  
package_arm_debug: 
 stage: package
 variables: 
 TYPE: '-t DEBUG'
 ARCH: '-a arm'
 VER: '-v n_$CI_PIPELINE_ID'
 BOOST: '-b 1_67_0'
 PROJECTS: '-p Ameli -p Parsifal'
 script: 
 - './opcua-plugin/gateway/helpers/opcua_packager/packageOPCUA.sh $TYPE $ARCH $VER $BOOST $PROJECT'
 
package_arm_release: 
 stage: package
  variables: 
 TYPE: '-t RELEASE'
 ARCH: '-a arm'
 VER: '-v n_$CI_PIPELINE_ID'
 BOOST: '-b 1_67_0'
 PROJECTS: '-p Ameli -p Parsifal'
 script: 
 - './opcua-plugin/gateway/helpers/opcua_packager/packageOPCUA.sh $TYPE $ARCH $VER $BOOST $PROJECT'
 
package_x86_debug:
 stage: package
 variables: 
 TYPE: '-t DEBUG'
 ARCH: '-a x86'
 VER: '-v n_$CI_PIPELINE_ID'
 BOOST: '-b 1_67_0'
 PROJECTS: '-p Ameli -p Parsifal'
 script: 
 - './opcua-plugin/gateway/helpers/opcua_packager/packageOPCUA.sh $TYPE $ARCH $VER $BOOST $PROJECT'

package_x86_release: 
 stage: package
 variables: 
 TYPE: '-t RELEASE'
 ARCH: '-a x86'
 VER: '-v n_$CI_PIPELINE_ID'
 BOOST: '-b 1_67_0'
 PROJECTS: '-p Ameli -p Parsifal'
 script: 
 - './opcua-plugin/gateway/helpers/opcua_packager/packageOPCUA.sh $TYPE $ARCH $VER $BOOST $PROJECT'