before_script: 
 - ./.check-dependencies

build_x86_server_release: 
 stage: build
 script: "./opcua-build-x86-amd64-release.sh"

build_x86_server_debug: 
 stage: build
 script: "./opcua-build-x86-amd64-debug.sh"

build_arm_server_release: 
 stage: build 
 script: "./opcua-build-arm-release.sh"

build_arm_server_debug:
 stage: build 
 script: "./opcua-build-arm-debug.sh"
