variables: 
 GIT_STRATEGY: fetch
 GIT_SUBMODULE_STRATEGY: recursive

stages: 
 - prep
 - build
 - package

apply_patches: 
 stage: prep 
 script: 
 - cd ./opcua-plugin/lwm2m-server 
 - git apply wakaama.patch 
 - cd ../../
 allow_failure: true
 
check_dependencies: 
 stage: prep
 script: 
 - './.check-dependencies -b ./../../../'

build_x86_server_release: 
 stage: build
 variables: 
  TYPE: '-t RELEASE'
  ARCH: '-a x86-amd64'
  BOOST: '-b /home/gitlab-runner/opcua-dev-workspace/boost-x86-amd64_1_67_0'
 script: 
  - './opcua-build-binaries.sh $TYPE $ARCH $BOOST'

build_x86_server_debug: 
 stage: build
 variables: 
  TYPE: '-t DEBUG'
  ARCH: '-a x86-amd64'
  BOOST: '-b /home/gitlab-runner/opcua-dev-workspace/boost-x86-amd64_1_67_0'
 script: 
  - './opcua-build-binaries.sh $TYPE $ARCH $BOOST'

build_arm_server_release: 
 stage: build
 variables: 
  TYPE: '-t RELEASE'
  ARCH: '-a arm'
  BOOST: '-b /home/gitlab-runner/opcua-dev-workspace/boost-arm_1_67_0'
  OPENSSL: '-s /home/gitlab-runner/opcua-dev-workspace/openssl'
  ODBC: '-d \/home\/gitlab-runner\/opcua-dev-workspace\/odbc-arm\/lib'
 script: 
  - './opcua-build-binaries.sh $TYPE $ARCH $BOOST $OPENSSL $ODBC'

build_arm_server_debug:
 stage: build
 variables: 
  TYPE: '-t DEBUG'
  ARCH: '-a arm'
  BOOST: '-b /home/gitlab-runner/opcua-dev-workspace/boost-arm_1_67_0'
   OPENSSL: '-s /home/gitlab-runner/opcua-dev-workspace/openssl'
  ODBC: '-d \/home\/gitlab-runner\/opcua-dev-workspace\/odbc-arm\/lib'
 script: 
  - './opcua-build-binaries.sh $TYPE $ARCH $BOOST $OPENSSL $ODBC'
  
package_arm_debug: 
 stage: package
 variables: 
  TYPE: '-t DEBUG'
  ARCH: '-a arm'
  VER: '-v n_$CI_PIPELINE_ID'
  BOOST: '-b 1_67_0'
  PROJECTS: '-p Ameli -p Parsifal'
 script: 
 - './opcua-plugin/gateway/helpers/opcua_packager/packageOPCUA.sh $TYPE $ARCH $VER $BOOST $PROJECT'
 
package_arm_release: 
 stage: package
 variables: 
  TYPE: '-t RELEASE'
  ARCH: '-a arm'
  VER: '-v n_$CI_PIPELINE_ID'
  BOOST: '-b 1_67_0'
  PROJECTS: '-p Ameli -p Parsifal'
 script: 
 - './opcua-plugin/gateway/helpers/opcua_packager/packageOPCUA.sh $TYPE $ARCH $VER $BOOST $PROJECT'
 
package_x86_debug:
 stage: package
 variables: 
  TYPE: '-t DEBUG'
  ARCH: '-a x86'
  VER: '-v n_$CI_PIPELINE_ID'
  BOOST: '-b 1_67_0'
  PROJECTS: '-p Ameli -p Parsifal'
 script: 
 - './opcua-plugin/gateway/helpers/opcua_packager/packageOPCUA.sh $TYPE $ARCH $VER $BOOST $PROJECT'

package_x86_release: 
 stage: package
 variables: 
  TYPE: '-t RELEASE'
  ARCH: '-a x86'
  VER: '-v n_$CI_PIPELINE_ID'
  BOOST: '-b 1_67_0'
  PROJECTS: '-p Ameli -p Parsifal'
 script: 
 - './opcua-plugin/gateway/helpers/opcua_packager/packageOPCUA.sh $TYPE $ARCH $VER $BOOST $PROJECT'